export const COLLAPSE_MENU = 'COLLAPSE_MENU';
export const COLLAPSE_TOGGLE = 'COLLAPSE_TOGGLE';

export const NAV_COLLAPSE_LEAVE = 'NAV_COLLAPSE_LEAVE';
export const NAV_CONTENT_LEAVE = 'NAV_CONTENT_LEAVE';

export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
export const ACCOUNT_INITIALIZE = 'ACCOUNT_INITIALIZE';

export const GET_DISTRICTS = 'GET_DISTRICTS';
export const GET_PALIKAS = 'GET_PALIKAS';
export const SELECTED_DISTRICTS = 'SELECTED_DISTRICTS';
export const SELECTED_PALIKAS = 'SELECTED_PALIKAS';
export const GET_WARDS = 'GET_WARDS';
export const SELECTED_WARDS = 'SELECTED_WARDS';

export const GET_PARTICIPANTS_BY_AGE = 'GET_PARTICIPANTS_BY_AGE';
export const GET_PARTICIPANTS_BY_GENDER = 'GET_PARTICIPANTS_BY_GENDER';
export const GET_PARTICIPANTS_BY_ETHINICITY = 'GET_PARTICIPANTS_BY_ETHINICITY';
export const GET_PARTICIPANTS = 'GET_PARTICIPANTS';

export const GET_DETAIL_USER_DATA = 'GET_DETAIL_USER_DATA';

// crs/hhRegistration/search
export const CRS_HH_REGISTRATION_DATA = 'CRS_HH_REGISTRATION_DATA';
export const CRS_TRANCHE_DATA = 'CRS_TRANCHE_DATA';

export const HEAD_PWD = 'HEAD_PWD';
export const OTHER_MEMBER_PWD = 'OTHER_MEMBER_PWD';
export const HH_TRANCHE_BASELINE = 'HH_TRANCHE_BASELINE';
export const HH_TRANCHE_CURRENT = 'HH_TRANCHE_CURRENT';

export const YEARS = 'YEARS';
export const SELECTED_YEARS = 'SELECTED_YEARS';
export const SELECTED_QUARTERS = 'SELECTED_QUARTERS';

export const SELECTED_STATE = 'SELECTED_STATE';
export const HH_CONSTRUCTION_TYPE = 'HH_CONSTRUCTION_TYPE';

export const HH_AVERAGE_EARN = 'HH_AVERAGE_EARN';

export const SELECTED = 'SELECTED';

export const KPI_MODEL_ONE_DATA = 'KPI_MODEL_ONE_DATA';
export const KPI_MODEL_TWO_DATA = 'KPI_MODEL_TWO_DATA';
export const KPI_MODEL_THREE_DATA = 'KPI_MODEL_THREE_DATA';
export const KPI_MODEL_FOUR_DATA = 'KPI_MODEL_FOUR_DATA';
export const KPI_MODEL_FIVE_DATA = 'KPI_MODEL_FIVE_DATA';


export const SECTOR_SELECTED = "SECTOR_SELECTED"

export const INDICATOR_SELECTED='INDICATOR_SELECTED'
